language: python
python:
- '3.6'
sudo: enabled
addons:
  apt:
    packages:
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin
    - libhdf5-serial-dev
    - gfortran
install:
- source continuous_integration/install.sh
- pip install matplotlib
- pip install LFPy
- pip install .
- pip install pytest
script: pytest
deploy:
  provider: pypi
  user: alejoe91
  on:
    branch: master
    tags: true
